name: ci-sonarcloud
on: 
  pull_request:
    branches:
      - dev

jobs:
  run-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm ci
      - run: npm run test:coverage